name: example
description: A new Flutter project.
publish_to: 'none'

version: 2.0.0

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.8
  dio: ^5.9.2
  faker: ^2.2.0
  file_picker: ^10.3.10
  file_saver: ^0.3.1
  flutter:
    sdk: flutter
  flutter_chat_core: 2.9.0
  flutter_chat_ui: 2.11.1
  flutter_login: ^5.0.0
  flutter_supabase_chat_core:
    path: ../
  flutter_svg: ^2.2.4
  http: ^1.6.0
  image_picker: ^1.2.1
  infinite_scroll_pagination: ^5.1.1
  intl: ^0.20.2
  open_filex: ^4.7.0
  path_provider: ^2.1.5
  supabase_flutter: ^2.12.0
  timeago: ^3.7.1


dev_dependencies:
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/