-- Migration to v2 for flutter_supabase_chat_core
-- This script is idempotent

DO
$$
    BEGIN
        -- 1. Aggiornamento tabella chats.users
        -- Unione firstName e lastName in name
        IF EXISTS (SELECT 1
                   FROM information_schema.columns
                   WHERE table_schema = 'chats' AND table_name = 'users' AND column_name = 'firstName') THEN
            IF NOT EXISTS (SELECT 1
                           FROM information_schema.columns
                           WHERE table_schema = 'chats' AND table_name = 'users' AND column_name = 'name') THEN
                ALTER TABLE chats.users
                    ADD COLUMN name text;
            END IF;

            UPDATE chats.users
            SET name = trim(concat(COALESCE("firstName", ''), ' ', COALESCE("lastName", '')))
            WHERE name IS NULL
               OR name = '';

            -- Rinomina imageUrl a imageSource
            IF EXISTS (SELECT 1
                       FROM information_schema.columns
                       WHERE table_schema = 'chats' AND table_name = 'users' AND column_name = 'imageUrl') THEN
                ALTER TABLE chats.users
                    RENAME COLUMN "imageUrl" TO "imageSource";
            END IF;

            -- Rimuovi vecchie colonne con CASCADE per gestire dipendenze (es. viste)
            ALTER TABLE chats.users
                DROP COLUMN IF EXISTS "firstName" CASCADE;
            ALTER TABLE chats.users
                DROP COLUMN IF EXISTS "lastName" CASCADE;
        END IF;

        -- 2. Aggiornamento tabella chats.rooms
        IF EXISTS (SELECT 1
                   FROM information_schema.columns
                   WHERE table_schema = 'chats' AND table_name = 'rooms' AND column_name = 'imageUrl') THEN
            -- Droppa la vista prima di rinominare se necessario per evitare errori di dipendenza
            DROP VIEW IF EXISTS chats.messages_l CASCADE;
            DROP VIEW IF EXISTS chats.rooms_l CASCADE;
            ALTER TABLE chats.rooms
                RENAME COLUMN "imageUrl" TO "imageSource";
        END IF;

        -- 2b. Aggiornamento tabella chats.messages
        IF EXISTS (SELECT 1
                   FROM information_schema.columns
                   WHERE table_schema = 'chats'
                     AND table_name = 'messages'
                     AND column_name = 'uri') THEN
            ALTER TABLE chats.messages
                RENAME COLUMN "uri" TO "source";
        END IF;

        -- 3. Creazione tabella chats.notifications (Punto 5)
        CREATE TABLE IF NOT EXISTS chats.notifications
        (
            id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            "createdAt" bigint NOT NULL DEFAULT (extract(epoch from now()) * 1000)::bigint,
            "roomId"    bigint REFERENCES chats.rooms (id) ON DELETE CASCADE,
            "messageId" bigint REFERENCES chats.messages (id) ON DELETE CASCADE,
            "authorId"  uuid REFERENCES auth.users (id) ON DELETE CASCADE,
            text        text,
            type        text,
            metadata    jsonb,
            "isRead"    boolean         DEFAULT false
        );

        -- Permessi per le notifiche
        GRANT ALL ON TABLE chats.notifications TO anon, authenticated, service_role;
        IF EXISTS (SELECT 1 FROM pg_sequences WHERE schemaname = 'chats' AND sequencename = 'notifications_id_seq') THEN
            GRANT ALL ON SEQUENCE chats.notifications_id_seq TO anon, authenticated, service_role;
        END IF;

        -- 4. Trigger per le notifiche
        -- Funzione per gestire l'inserimento di notifiche quando arriva un messaggio
        CREATE OR REPLACE FUNCTION chats.handle_new_notification()
            RETURNS trigger
            LANGUAGE 'plpgsql'
            SECURITY DEFINER
        AS
        $BODY$
        BEGIN
            INSERT INTO chats.notifications ("roomId", "messageId", "authorId", text, type, metadata)
            VALUES (NEW."roomId", NEW.id, NEW."authorId", NEW.text, NEW.type, NEW.metadata);
            RETURN NEW;
        END;
        $BODY$;

        DROP TRIGGER IF EXISTS on_message_inserted ON chats.messages;
        CREATE TRIGGER on_message_inserted
            AFTER INSERT
            ON chats.messages
            FOR EACH ROW
        EXECUTE PROCEDURE chats.handle_new_notification();

        -- 5. Ripristino delle viste (sempre eseguito per garantire l'allineamento alla v2)
        DROP VIEW IF EXISTS chats.messages_l CASCADE;
        DROP VIEW IF EXISTS chats.rooms_l CASCADE;

        EXECUTE 'create or replace view chats.rooms_l
        with (security_invoker=''on'') as
    select r.id,
           r."imageSource",
           r.metadata,
           case
               when r.type = ''direct'' and auth.uid() is not null then
                   (select u.name
                    from chats.users u
                    where u.id = any (r."userIds")
                      and u.id <> auth.uid()
                    limit 1)
               else
                   r.name
               end                          as name,
           r.type,
           r."userIds",
           r."lastMessages",
           r."userRoles",
           r."createdAt",
           r."updatedAt",
           (select jsonb_agg(to_jsonb(u))
            from chats.users u
            where u.id = any (r."userIds")) as users
    from chats.rooms r';

        EXECUTE 'create or replace view chats.messages_l
    with (security_invoker=''on'') as
select m.id,
       m."createdAt",
       m.metadata,
       m.duration,
       m."mimeType",
       m.name,
       m."remoteId",
       m."repliedMessage",
       m."roomId",
       m."showStatus",
       m.size,
       m.status,
       m.type,
       m."updatedAt",
       m.source,
       m."waveForm",
       m."isLoading",
       m.height,
       m.width,
       m."previewData",
       m."authorId",
       m.text,
       to_jsonb(u) as author,
       to_jsonb(r) as room
from chats.messages m
         left join chats.users u on u.id = m."authorId"
         left join chats.rooms_l r on r.id = m."roomId"';
    END
$$;

-- Abilita RLS per le notifiche
ALTER TABLE chats.notifications
    ENABLE ROW LEVEL SECURITY;

-- Policy per le notifiche: l'utente può leggere solo le notifiche delle stanze a cui appartiene
DROP POLICY IF EXISTS "Users can view their own notifications" ON chats.notifications;
CREATE POLICY "Users can view their own notifications" ON chats.notifications
    FOR SELECT
    TO authenticated
    USING (
    EXISTS (SELECT 1
            FROM chats.rooms r
            WHERE r.id = chats.notifications."roomId"
              AND auth.uid() = ANY (r."userIds"))
    );

-- Policy per segnare come letto
DROP POLICY IF EXISTS "Users can update their own notifications" ON chats.notifications;
CREATE POLICY "Users can update their own notifications" ON chats.notifications
    FOR UPDATE
    TO authenticated
    USING (
    EXISTS (SELECT 1
            FROM chats.rooms r
            WHERE r.id = chats.notifications."roomId"
              AND auth.uid() = ANY (r."userIds"))
    )
    WITH CHECK (
    EXISTS (SELECT 1
            FROM chats.rooms r
            WHERE r.id = chats.notifications."roomId"
              AND auth.uid() = ANY (r."userIds"))
    );

-- Aggiungi alla pubblicazione realtime
DO
$$
    BEGIN
        IF NOT EXISTS (SELECT 1
                       FROM pg_publication_tables
                       WHERE pubname = 'supabase_realtime'
                         AND schemaname = 'chats'
                         AND tablename = 'notifications') THEN
            ALTER PUBLICATION supabase_realtime ADD TABLE chats.notifications;
        END IF;
    END
$$;
